FROM node:16-alpine
USER node
#WORKDIR '/app'
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
#COPY ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
#COPY . .
CMD ["npm","start"]
#CMD ["npm","run", "start"]